#!/bin/bash

# prevent apron from being sourced more than once
[[ -v APRON_state ]] && return 0

shopt -s extglob

modules=('assert'
         'mock'
         'testcase')

for m in "${modules[@]}"; do
  . "${0%/*}/apron-$m" "$@"
done
unset m modules

# Mark as much as possible readonly. This is pretty dirty, but we don't
# want the calling environment to mess with us.
readonly $(compgen -A function APRON_; compgen -A function _APRON_)
readonly APRON_rootdir=${0%/*}
readonly APRON_state_disabled=0
readonly APRON_state_enabled=1
readonly APRON_state_paused=2
APRON_state=$APRON_state_disabled

# vim: set ft=sh et ts=2 sw=2:
